apiVersion: v1
kind: Service
metadata:
  name: java-stock-api
  namespace: stock-analyser
spec:
  type: ClusterIP
  selector:
    app: java-stock-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
